### ISSUE TITLE
"java.nio.file.NoSuchFileException: ../thewebapp" thrown when running assembled war file, 

### ISSUE THREAD

**Issue by yogendra** [jetty-project/embedded-jetty-live-war#1]
I tried to run war file in local repository from a directory outside project tree. Command looked like:

``` shell
yogendra@mac:/tmp>java -jar ~/.m2/repository/org/eclipse/jetty/demo/livewar/livewar-assembly/1-SNAPSHOT/livewar-assembly-1-SNAPSHOT.war
Using ClassLoader: jetty.bootstrap.LiveWarClassLoader[file:/Users/yogendra/.m2/repository/org/eclipse/jetty/demo/livewar/livewar-assembly/1-SNAPSHOT/livewar-assembly-1-SNAPSHOT.war]
2016-10-20 01:42:14.157:INFO::main: Logging initialized @171ms
java.nio.file.NoSuchFileException: ../thewebapp
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
    at jetty.livewar.ServerMain.getOperationalMode(ServerMain.java:82)
    at jetty.livewar.ServerMain.run(ServerMain.java:45)
    at jetty.livewar.ServerMain.main(ServerMain.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at jetty.bootstrap.JettyBootstrap.main(JettyBootstrap.java:47)
```

**Comment by joakime** [comment]
Fixed in branches `jetty-9.4.x` and `jetty-10.0.x` and `jetty-11.0.x`
